### ISSUE TITLE
恢复钱包界面密码输入框内无法输入“*#”等这类字符。

### ISSUE THREAD

**Issue by Garry2015** [XDagger/android-wallet#16]
恢复钱包界面密码输入框内无法输入“*#”等这类字符。
我的密码含有#字符，目前无法输入该类字符。

**Comment by ssyijiu** [comment]
The same is true for the current QT wallet, mainly considering the difference between the half-width and the full-width when the user sets the password, for example, typing ' and ' is not a character at all. Not compatible with the original wallet password is really embarrassing, let us consider it.

目前 QT 钱包也是这样，主要考虑到用户设置密码时半角和全角的区分，例如输入 ' 和 ’ ，完全不是一个字符。不兼容最初的钱包密码确实很尴尬，我们再考虑下。

**Comment by ssyijiu** [comment]
Fixed in release 0.2.2
