### ISSUE TITLE
Cannot install apk after a remove of it.

### ISSUE THREAD

**Issue by Sofarlemineur** [XDagger/android-wallet#18]
I have downloaded the releases from github, installed it without any issues.
But at first start i was on a page filled in Chinese, so i removed the apk, and then try to reinstall it, without any success for now...

**Comment by ssyijiu** [comment]
Prompt what can't be installed, can you take a screenshot?

**Comment by PegasusCharles** [comment]
Should be a problem with Chinese and English adaptation
