### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 colum 1 path $

### ISSUE THREAD

**Issue by mathsw** [XDagger/android-wallet#23]
When refreshing (swiping down) in the Home view, this message appears.

![](https://i.imgur.com/fXLUMKH.png)

**Comment by ssyijiu** [comment]
Can you copy the address of your picture to me? Let me check the reason.

**Comment by One8zero3** [comment]
I have the same issue 
https://ibb.co/c6enWK

**Comment by mathsw** [comment]
@ssyijiu The address in the picture: 6vzCszS4H26jcuNV28V1cyggLoM47X7S

**Comment by One8zero3** [comment]
when it connects to main net my phone instantly vibrates alerting new error , the same one as mathsw and every time you refresh home page same error appear

**Comment by ssyijiu** [comment]
@mathsw @One8zero3 
The transfer record We used a api interface from a mine pool, because the mine pool upgrade, this interface call failed, I am contacting them to fix.

**Comment by ssyijiu** [comment]
Fixed in release 0.2.2
