### ISSUE TITLE
Eternal loading after send some xdag to one another wallet

### ISSUE THREAD

**Issue by Sofarlemineur** [XDagger/android-wallet#75]
Hi there,
On my Samsung J5 2016, with 0.2.3 release, when I send some xdag to one another wallet, refresh is stuck, I mean, display responding but it loads with no end, I let it run 10 minutes before kill the app, and then retry, with the same issue.
All tx have been made, but it seems that there is a problem with the refresh.

Still up to reply if need any more info.
Thanks for your work

**Comment by ssyijiu** [comment]
Is your wallet address the address used for mining?

**Comment by Sofarlemineur** [comment]
hi,
Not its not

**Comment by ssyijiu** [comment]
What is your wallet address?
